//! System-level identifiers.
//!
//! This module defines the strongly-typed identifier newtypes used across
//! OMNI OS. Every identifier kind has its own type so the compiler rejects
//! accidental conflation (e.g., passing a [`ModelId`] where a [`NodeId`] is
//! expected).
//!
//! # Identifier zoo
//!
//! | Type | Backing | Source of truth | Lifetime |
//! |---|---|---|---|
//! | [`NodeId`]       | `[u8; 32]` | TEE attestation report hash (BLAKE3) | Persistent — re-derivable from quote |
//! | [`ModelId`]      | `[u8; 32]` | Content-addressed hash of signed model manifest | Persistent |
//! | [`AgentId`]      | `Uuid` (v7) | Generated by the host node when an agent starts | Process-scoped |
//! | [`CapabilityId`] | `Uuid` (v7) | Generated by the capability issuer | Token-TTL-scoped |
//! | [`SessionId`]    | `Uuid` (v7) | Generated by the runtime when an inference session opens | Session-scoped |
//!
//! # Why no `core::fmt::Display`?
//!
//! These identifiers can transit through logs, traces, and metrics. A naive
//! `format!("{}", node_id)` would dump 32 bytes of attestation hash into a
//! log file, which is both unreadable and an audit liability. We omit
//! `Display` entirely. To surface an identifier explicitly, callers must
//! invoke [`IdHex::to_hex`], which is `grep`-friendly and reviewable.
//!
//! `Debug` is implemented but renders a truncated hex prefix so that
//! `tracing::debug!(?node_id)` produces a useful but bounded view.
//!
//! # Construction trust boundaries
//!
//! Each identifier exposes a constructor whose name documents where the
//! input must come from. For example, [`NodeId::from_attestation_hash`]
//! takes the BLAKE3 digest of a TEE quote — the caller is responsible for
//! having verified the quote first. Constructors that accept arbitrary
//! bytes (e.g., for deserialization) are namespaced (`from_bytes`) so
//! audit grep can find them.
//!
//! # `no_std` notes
//!
//! All types are `no_std + alloc`-compatible. Hex encoding uses [`alloc`]
//! buffers; no allocation is performed for equality / ordering.

use alloc::string::String;
use alloc::vec::Vec;
use core::fmt;

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use zeroize::Zeroize;

// Helper used by AgentId / CapabilityId / SessionId to produce 16 random
// bytes from the platform CSPRNG. We invoke `getrandom` directly rather
// than going through `uuid`'s built-in `new_v4` so we can stay
// `no_std`-only and depend on a single entropy source for the workspace.
//
// Failure to obtain entropy is unrecoverable on a system that needs
// authentication / capability tokens to function — we panic with a
// stable message rather than swallow the error and emit predictable IDs.
fn random_uuid_bytes() -> [u8; 16] {
    let mut bytes = [0u8; 16];
    // Panic message is the stable contract: tests and probes can match on
    // it. Do not change without bumping a major version.
    //
    // `expect_used` is an intentional escape hatch here: a CSPRNG failure
    // is unrecoverable for OMNI OS (capability tokens, signatures, and
    // attestation all hinge on entropy). Returning a `Result` from this
    // helper would force every identifier constructor in the workspace
    // to be fallible, which is worse ergonomically and does not improve
    // the worst-case behaviour — the caller's only sensible response to
    // entropy failure is to abort.
    #[allow(clippy::expect_used)]
    getrandom::getrandom(&mut bytes)
        .expect("OMNI: CSPRNG (getrandom) failed — system entropy is unavailable");
    // Set the four most significant bits of byte 6 to 0100 (UUID version 4).
    // Set the two most significant bits of byte 8 to 10 (RFC 4122 variant).
    // This produces a valid UUIDv4 layout from arbitrary random bytes —
    // the same bit-twiddle that `uuid`'s `new_v4()` performs internally.
    // `indexing_slicing` is allowed because the indices 6 and 8 are
    // compile-time constants strictly less than the array length 16.
    #[allow(clippy::indexing_slicing)]
    {
        bytes[6] = (bytes[6] & 0x0F) | 0x40;
        bytes[8] = (bytes[8] & 0x3F) | 0x80;
    }
    bytes
}

// =============================================================================
// IdHex trait — opt-in surfacing helper.
// =============================================================================

/// Helper trait implemented by every identifier in this module.
///
/// Centralises the conversion to/from hex strings so callers always go
/// through an auditable code path when an identifier needs to leave the
/// process boundary (logs, metrics, wire formats meant for humans).
pub trait IdHex: Sized {
    /// Encode this identifier as a lowercase hex string. Allocates.
    fn to_hex(&self) -> String;

    /// Decode an identifier from a hex string. Returns `None` on length
    /// mismatch or invalid hex digits — never panics.
    fn from_hex(s: &str) -> Option<Self>;
}

// Internal helper: render a fixed-size byte array as a Debug-friendly
// `Type(<8-hex-prefix>…)` string. We intentionally truncate so
// `tracing::debug!(?node_id)` does not flood logs with full digests.
//
// SECURITY: never widen this prefix without auditing every log site that
// carries identifiers. The 8-char prefix is short enough to remain
// non-correlatable across logs but long enough to disambiguate within a
// single trace (~2^32 distinct prefixes).
fn fmt_truncated(name: &str, bytes: &[u8], f: &mut fmt::Formatter<'_>) -> fmt::Result {
    write!(f, "{name}(")?;
    // Render the first 4 bytes (= 8 hex chars). Manual loop avoids pulling
    // in `core::fmt::Write::write_fmt`'s formatter machinery for byte
    // slices, which is awkward with the `hex` crate's no_std API.
    for b in bytes.iter().take(4) {
        write!(f, "{b:02x}")?;
    }
    write!(f, "…)")
}

// =============================================================================
// NodeId — TEE-attested hardware identity.
// =============================================================================

/// Globally unique identifier of an OMNI OS node.
///
/// A `NodeId` is the BLAKE3 digest of the node's TEE attestation quote.
/// It is therefore:
///
/// * **Deterministic** — re-deriving the hash from the same quote yields
///   the same `NodeId`.
/// * **Unforgeable** — minting a `NodeId` for hardware you do not own
///   requires either compromising the TEE root of trust or finding a
///   BLAKE3 collision (assumed infeasible).
/// * **Stable across reboots** — the quote's measurement covers the
///   firmware identity, not session state.
///
/// # Construction
///
/// In production, `NodeId` is constructed via [`NodeId::from_attestation_hash`]
/// after the caller has verified a TEE quote (Phase 1 = `omni-tee` — see
/// `/todo.md` P5). The [`NodeId::from_bytes`] constructor exists for
/// deserialization paths only and should not be used to manufacture node
/// identities at runtime.
#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize, Zeroize)]
pub struct NodeId([u8; 32]);

impl NodeId {
    /// Length of the underlying byte representation, in bytes.
    pub const LEN: usize = 32;

    /// Construct a `NodeId` from the BLAKE3 hash of a verified TEE
    /// attestation quote.
    ///
    /// The caller is responsible for having verified the quote first
    /// (P5 — `omni-tee`). Passing an unverified hash bypasses the trust
    /// boundary and is a misuse of this API.
    #[must_use]
    pub const fn from_attestation_hash(hash: [u8; 32]) -> Self {
        Self(hash)
    }

    /// Construct a `NodeId` from raw bytes.
    ///
    /// Reserved for deserialization paths. Production code should prefer
    /// [`NodeId::from_attestation_hash`] which documents the trust origin.
    #[must_use]
    pub const fn from_bytes(bytes: [u8; 32]) -> Self {
        Self(bytes)
    }

    /// Borrow the underlying bytes.
    #[must_use]
    pub const fn as_bytes(&self) -> &[u8; 32] {
        &self.0
    }
}

impl fmt::Debug for NodeId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        fmt_truncated("NodeId", &self.0, f)
    }
}

impl IdHex for NodeId {
    fn to_hex(&self) -> String {
        hex::encode(self.0)
    }

    fn from_hex(s: &str) -> Option<Self> {
        let mut buf = [0u8; 32];
        hex::decode_to_slice(s, &mut buf).ok()?;
        Some(Self(buf))
    }
}

// =============================================================================
// ModelId — content-addressed model identity.
// =============================================================================

/// Content-addressed identifier of a signed model manifest.
///
/// `ModelId` is the BLAKE3 digest of the manifest's canonical encoding.
/// Two nodes that load the same manifest derive the same `ModelId`,
/// which lets the mesh deduplicate model state without trusting any
/// authority's "model name → bytes" mapping.
#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize, Zeroize)]
pub struct ModelId([u8; 32]);

impl ModelId {
    /// Length of the underlying byte representation, in bytes.
    pub const LEN: usize = 32;

    /// Construct from the BLAKE3 hash of a signed model manifest.
    ///
    /// The signature on the manifest is verified upstream (Phase 2 —
    /// model loader). This constructor only encodes the trust boundary
    /// in the type name; it does not perform verification itself.
    #[must_use]
    pub const fn from_manifest_hash(hash: [u8; 32]) -> Self {
        Self(hash)
    }

    /// Construct from raw bytes (deserialization path).
    #[must_use]
    pub const fn from_bytes(bytes: [u8; 32]) -> Self {
        Self(bytes)
    }

    /// Borrow the underlying bytes.
    #[must_use]
    pub const fn as_bytes(&self) -> &[u8; 32] {
        &self.0
    }
}

impl fmt::Debug for ModelId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        fmt_truncated("ModelId", &self.0, f)
    }
}

impl IdHex for ModelId {
    fn to_hex(&self) -> String {
        hex::encode(self.0)
    }

    fn from_hex(s: &str) -> Option<Self> {
        let mut buf = [0u8; 32];
        hex::decode_to_slice(s, &mut buf).ok()?;
        Some(Self(buf))
    }
}

// =============================================================================
// UUID-backed identifiers (AgentId, CapabilityId, SessionId).
// =============================================================================
//
// These three identifiers are all UUIDv7 — sortable, time-ordered, 128 bit.
// We define them as distinct newtypes so the compiler enforces the
// distinction (`fn revoke(cap: CapabilityId)` cannot accidentally accept a
// `SessionId`). The shared backing type is hidden as an implementation
// detail.
//
// UUIDv7 was chosen over v4 because its leading 48 bits are a
// millisecond-precision timestamp, which gives:
//   1. Better cache locality in B-tree-backed stores (e.g., the
//      revocation list in `omni-capability`).
//   2. A natural "issued at" hint for debugging without an extra field.
//
// We do not rely on the timestamp for security. The capability token
// carries an explicit `not_before` / `not_after` window (see P1.3.a).

/// Local identifier of an AI agent within a node.
///
/// Generated when the agent starts. Lifetime is bound to the agent's
/// process; reusing an `AgentId` after process exit is not allowed.
///
/// `Zeroize` is implemented manually (not derived) because `uuid::Uuid`
/// does not implement `Zeroize`. The manual implementation overwrites
/// the inner UUID with the nil UUID (all zeroes), achieving the same
/// invariant as the derive macro would for a `[u8; 16]` field.
#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub struct AgentId(Uuid);

impl Zeroize for AgentId {
    fn zeroize(&mut self) {
        self.0 = Uuid::nil();
    }
}

impl AgentId {
    /// Length of the underlying byte representation, in bytes.
    pub const LEN: usize = 16;

    /// Generate a fresh `UUIDv4` identifier.
    ///
    /// Requires a working CSPRNG (`getrandom`). Panics in environments
    /// without a randomness source — these are not supported targets.
    ///
    /// # Panics
    ///
    /// Panics if `getrandom` cannot produce entropy on the current platform.
    /// On Linux this means `getrandom(2)` returned an unrecoverable error.
    /// The panic message is part of the stable contract; do not change
    /// without bumping a major version.
    #[must_use]
    pub fn new() -> Self {
        Self(Uuid::from_bytes(random_uuid_bytes()))
    }

    /// Construct from raw bytes (deserialization path).
    #[must_use]
    pub const fn from_bytes(bytes: [u8; 16]) -> Self {
        Self(Uuid::from_bytes(bytes))
    }

    /// Borrow the underlying bytes.
    #[must_use]
    pub fn as_bytes(&self) -> &[u8; 16] {
        self.0.as_bytes()
    }
}

impl fmt::Debug for AgentId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        fmt_truncated("AgentId", self.0.as_bytes(), f)
    }
}

impl IdHex for AgentId {
    fn to_hex(&self) -> String {
        hex::encode(self.0.as_bytes())
    }

    fn from_hex(s: &str) -> Option<Self> {
        let mut buf = [0u8; 16];
        hex::decode_to_slice(s, &mut buf).ok()?;
        Some(Self(Uuid::from_bytes(buf)))
    }
}

/// Identifier of a capability token.
///
/// Generated by the capability issuer when minting or attenuating a token.
/// The `CapabilityId` is also the lookup key in the revocation list
/// (`omni-capability::revocation`).
///
/// See [`AgentId`] for the rationale on the manual `Zeroize` impl.
#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub struct CapabilityId(Uuid);

impl Zeroize for CapabilityId {
    fn zeroize(&mut self) {
        self.0 = Uuid::nil();
    }
}

impl CapabilityId {
    /// Length of the underlying byte representation, in bytes.
    pub const LEN: usize = 16;

    /// Generate a fresh `UUIDv4` identifier.
    ///
    /// # Panics
    ///
    /// See [`AgentId::new`]. Same CSPRNG, same panic semantics.
    #[must_use]
    pub fn new() -> Self {
        Self(Uuid::from_bytes(random_uuid_bytes()))
    }

    /// Construct from raw bytes (deserialization path).
    #[must_use]
    pub const fn from_bytes(bytes: [u8; 16]) -> Self {
        Self(Uuid::from_bytes(bytes))
    }

    /// Borrow the underlying bytes.
    #[must_use]
    pub fn as_bytes(&self) -> &[u8; 16] {
        self.0.as_bytes()
    }
}

impl fmt::Debug for CapabilityId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        fmt_truncated("CapabilityId", self.0.as_bytes(), f)
    }
}

impl IdHex for CapabilityId {
    fn to_hex(&self) -> String {
        hex::encode(self.0.as_bytes())
    }

    fn from_hex(s: &str) -> Option<Self> {
        let mut buf = [0u8; 16];
        hex::decode_to_slice(s, &mut buf).ok()?;
        Some(Self(Uuid::from_bytes(buf)))
    }
}

/// Identifier of an inference session.
///
/// A session groups a sequence of related inference calls (typically a
/// conversation turn or batch). Short-lived; rotated when the session is
/// closed or times out.
///
/// See [`AgentId`] for the rationale on the manual `Zeroize` impl.
#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub struct SessionId(Uuid);

impl Zeroize for SessionId {
    fn zeroize(&mut self) {
        self.0 = Uuid::nil();
    }
}

impl SessionId {
    /// Length of the underlying byte representation, in bytes.
    pub const LEN: usize = 16;

    /// Generate a fresh `UUIDv4` identifier.
    ///
    /// # Panics
    ///
    /// See [`AgentId::new`]. Same CSPRNG, same panic semantics.
    #[must_use]
    pub fn new() -> Self {
        Self(Uuid::from_bytes(random_uuid_bytes()))
    }

    /// Construct from raw bytes (deserialization path).
    #[must_use]
    pub const fn from_bytes(bytes: [u8; 16]) -> Self {
        Self(Uuid::from_bytes(bytes))
    }

    /// Borrow the underlying bytes.
    #[must_use]
    pub fn as_bytes(&self) -> &[u8; 16] {
        self.0.as_bytes()
    }
}

impl fmt::Debug for SessionId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        fmt_truncated("SessionId", self.0.as_bytes(), f)
    }
}

impl IdHex for SessionId {
    fn to_hex(&self) -> String {
        hex::encode(self.0.as_bytes())
    }

    fn from_hex(s: &str) -> Option<Self> {
        let mut buf = [0u8; 16];
        hex::decode_to_slice(s, &mut buf).ok()?;
        Some(Self(Uuid::from_bytes(buf)))
    }
}

// Default impls for the runtime-generated identifiers. Provided as a
// convenience for collections and tests; semantically equivalent to `new()`.
impl Default for AgentId {
    fn default() -> Self {
        Self::new()
    }
}

impl Default for CapabilityId {
    fn default() -> Self {
        Self::new()
    }
}

impl Default for SessionId {
    fn default() -> Self {
        Self::new()
    }
}

// =============================================================================
// Bulk hex helpers used by the encrypted module + tests.
// =============================================================================

/// Convert any byte slice to lowercase hex. Allocates.
///
/// Public so other crates in the workspace can use the same convention
/// without re-importing `hex` directly.
#[must_use]
pub fn bytes_to_hex(bytes: &[u8]) -> String {
    hex::encode(bytes)
}

/// Decode a hex string into a freshly-allocated byte vector.
///
/// Returns `None` on invalid hex digits; never panics.
#[must_use]
pub fn hex_to_bytes(s: &str) -> Option<Vec<u8>> {
    hex::decode(s).ok()
}

// =============================================================================
// Tests
// =============================================================================

#[cfg(test)]
mod tests {
    use super::*;
    use proptest::prelude::*;

    // -------------------------------------------------------------------------
    // Round-trip tests: byte-array -> ID -> byte-array.
    // -------------------------------------------------------------------------

    #[test]
    fn node_id_round_trip_bytes() {
        let bytes = [42u8; 32];
        let id = NodeId::from_attestation_hash(bytes);
        assert_eq!(id.as_bytes(), &bytes);
    }

    #[test]
    fn model_id_round_trip_bytes() {
        let bytes = [7u8; 32];
        let id = ModelId::from_manifest_hash(bytes);
        assert_eq!(id.as_bytes(), &bytes);
    }

    // -------------------------------------------------------------------------
    // Hex round-trip.
    // -------------------------------------------------------------------------

    #[test]
    fn node_id_hex_round_trip() {
        let original = NodeId::from_attestation_hash([0xAB; 32]);
        let hex = original.to_hex();
        // 32 bytes = 64 hex chars.
        assert_eq!(hex.len(), 64);
        let decoded = NodeId::from_hex(&hex).expect("valid hex round-trip");
        assert_eq!(original, decoded);
    }

    #[test]
    fn capability_id_hex_round_trip() {
        let original = CapabilityId::new();
        let hex = original.to_hex();
        assert_eq!(hex.len(), 32); // 16 bytes = 32 hex chars
        let decoded = CapabilityId::from_hex(&hex).expect("valid hex round-trip");
        assert_eq!(original, decoded);
    }

    // -------------------------------------------------------------------------
    // `from_hex` does not panic on garbage input.
    // -------------------------------------------------------------------------

    #[test]
    fn node_id_from_hex_rejects_wrong_length() {
        assert!(NodeId::from_hex("too short").is_none());
        assert!(NodeId::from_hex("").is_none());
    }

    #[test]
    fn node_id_from_hex_rejects_invalid_chars() {
        // 64 chars but with a non-hex character. Using `format!` keeps us
        // inside the `core::fmt` machinery without needing `ToString` in scope
        // (we are `no_std + alloc`, so `ToString` is not in the default
        // prelude).
        let bad = alloc::format!("ZZ{}", "00".repeat(31));
        assert!(NodeId::from_hex(&bad).is_none());
    }

    // -------------------------------------------------------------------------
    // UUIDv7-based IDs are unique across calls (very high probability).
    // -------------------------------------------------------------------------

    #[test]
    fn agent_id_new_is_unique() {
        let a = AgentId::new();
        let b = AgentId::new();
        // Probability of collision in two consecutive UUIDv7s is ~2^-74 due
        // to the random component; assertion is statistically safe.
        assert_ne!(a, b);
    }

    #[test]
    fn capability_id_new_is_unique() {
        let a = CapabilityId::new();
        let b = CapabilityId::new();
        assert_ne!(a, b);
    }

    #[test]
    fn session_id_new_is_unique() {
        let a = SessionId::new();
        let b = SessionId::new();
        assert_ne!(a, b);
    }

    // -------------------------------------------------------------------------
    // Debug output is bounded and never reveals the full identifier.
    // -------------------------------------------------------------------------

    #[test]
    fn debug_output_is_truncated() {
        let id = NodeId::from_attestation_hash([0xFF; 32]);
        let dbg = alloc::format!("{id:?}");
        // "NodeId(ffffffff…)" is 18 chars; full hex would be 70+. Assert
        // bounded — this is the security invariant we care about.
        assert!(
            dbg.len() < 30,
            "debug output unexpectedly long: {dbg} ({})",
            dbg.len()
        );
        assert!(dbg.contains("NodeId"));
        assert!(dbg.contains('…'));
    }

    // -------------------------------------------------------------------------
    // Determinism: identical inputs -> identical IDs.
    // -------------------------------------------------------------------------

    proptest! {
        #[test]
        fn node_id_determinism(bytes in proptest::array::uniform32(any::<u8>())) {
            let a = NodeId::from_attestation_hash(bytes);
            let b = NodeId::from_attestation_hash(bytes);
            prop_assert_eq!(a, b);
        }

        #[test]
        fn model_id_determinism(bytes in proptest::array::uniform32(any::<u8>())) {
            let a = ModelId::from_manifest_hash(bytes);
            let b = ModelId::from_manifest_hash(bytes);
            prop_assert_eq!(a, b);
        }

        // Distinct inputs -> distinct IDs (collision-free in 32 bytes is
        // a property of the underlying hash, but here we test the wrapper:
        // it must not lose entropy by truncation or normalisation).
        #[test]
        fn node_id_distinct_inputs_distinct_ids(
            a_bytes in proptest::array::uniform32(any::<u8>()),
            b_bytes in proptest::array::uniform32(any::<u8>()),
        ) {
            prop_assume!(a_bytes != b_bytes);
            let a = NodeId::from_attestation_hash(a_bytes);
            let b = NodeId::from_attestation_hash(b_bytes);
            prop_assert_ne!(a, b);
        }

        // Hex round-trip is total over all 32-byte inputs.
        #[test]
        fn node_id_hex_round_trip_total(bytes in proptest::array::uniform32(any::<u8>())) {
            let id = NodeId::from_attestation_hash(bytes);
            let hex = id.to_hex();
            let decoded = NodeId::from_hex(&hex).expect("round-trip cannot fail");
            prop_assert_eq!(id, decoded);
        }

        #[test]
        fn model_id_hex_round_trip_total(bytes in proptest::array::uniform32(any::<u8>())) {
            let id = ModelId::from_manifest_hash(bytes);
            let hex = id.to_hex();
            let decoded = ModelId::from_hex(&hex).expect("round-trip cannot fail");
            prop_assert_eq!(id, decoded);
        }
    }

    // -------------------------------------------------------------------------
    // Ordering: derived `Ord` is consistent with byte-level ordering.
    // -------------------------------------------------------------------------

    #[test]
    fn node_id_ordering_matches_byte_order() {
        let smaller = NodeId::from_attestation_hash([0x00; 32]);
        let larger = NodeId::from_attestation_hash([0xFF; 32]);
        assert!(smaller < larger);
    }
}
