//! OMNI OS kernel-runner entry point.
//!
//! Specified by [`OIP-Kernel-005`] § S2. This binary is compiled for
//! `x86_64-unknown-none` and is the **bootable** artifact: the
//! bootloader hands `_start` (generated by [`entry_point!`]) the
//! `BootInfo` struct, the runner extracts the GOP framebuffer (if any),
//! initialises the heap, and forwards into `omni_kernel::kmain`.

#![no_std]
#![no_main]
#![allow(unsafe_code)]
#![allow(clippy::missing_docs_in_private_items)]

use bootloader_api::{entry_point, BootInfo, BootloaderConfig};
use bootloader_api::config::Mapping;
use bootloader_api::info::PixelFormat as BPF;
use omni_kernel::bare_metal::graphics::{FrameBuffer, PixelFormat};

mod early_console;

/// Bootloader configuration: request dynamic physical-memory mapping.
///
/// Framebuffer resolution is configured in the `disk-image` builder
/// (via `bootloader::UefiBoot`) rather than here; `bootloader_api 0.11`
/// moved that concern to the host-side build step.
///
/// **MB12 bare-metal limitation:** the kernel ELF is linked as
/// `ET_EXEC` with `p_vaddr = 0x200000` (PML4 index 0). The
/// `BootloaderConfig::mappings.dynamic_range_start` field only honours
/// `ET_DYN` kernels, which Rust's `x86_64-unknown-none` target spec
/// does not currently produce (`-C relocation-model=static` +
/// `--no-pie` remain mandatory to keep the bootloader happy on the
/// build path). Consequence: the kernel image lives in the low half,
/// so the per-process `AddressSpace::new_with_kernel_half` clone
/// (which mirrors only PML4 indices 256..511) loses the kernel image
/// when `mov cr3` switches to a per-process PML4. The first instruction
/// fetch after the CR3 reload triple-faults, which manifests as the VM
/// going to `stopped` after the `[sched] entering Ring 3 via iretq`
/// trace line under `mb12-userprobe`. Tracked as the headline MB13
/// follow-up alongside the SIMD ICE on `omni-crypto`.
static BOOTLOADER_CONFIG: BootloaderConfig = {
    let mut cfg = BootloaderConfig::new_default();
    cfg.mappings.physical_memory = Some(Mapping::Dynamic);
    cfg
};

entry_point!(kernel_entry, config = &BOOTLOADER_CONFIG);

/// Entry point invoked by the bootloader after UEFI exit-boot-services.
///
/// 1. Initialise the early console (COM1 serial).
/// 2. Extract the GOP framebuffer from `BootInfo` (if present).
/// 3. Select the kernel heap region and install it into `GLOBAL_HEAP`.
/// 4. Hand control to [`omni_kernel::kmain`].
fn kernel_entry(boot_info: &'static mut BootInfo) -> ! {
    // Debug-port probe: write 'K' to QEMU's debug console (port 0xE9).
    // SAFETY: port 0xE9 is QEMU's debug exit/console port; harmless on real hw.
    unsafe { omni_kernel::bare_metal::arch::outb(0xE9, b'K') };

    // Disable maskable interrupts immediately.
    omni_kernel::bare_metal::arch::interrupts::disable();

    // Initialise the 16550 UART on COM1.
    omni_kernel::bare_metal::early_console::init();

    // Step 1 — early console banner (pre-heap, K3 invariant proof).
    early_console::announce_boot();

    // Step 2 — extract GOP framebuffer before heap init (no alloc needed).
    // In bootloader_api 0.11, `BootInfo.framebuffer` is `Option<FrameBuffer>`
    // (standard Rust Option, not the legacy `Optional<T>` wrapper).
    let fb: Option<FrameBuffer> = boot_info.framebuffer.take().map(|raw| {
        let info = raw.info();
        let format = match info.pixel_format {
            BPF::Rgb => PixelFormat::Rgb,
            BPF::Bgr => PixelFormat::Bgr,
            BPF::U8  => PixelFormat::U8,
            _        => PixelFormat::Other,
        };
        // Framebuffer dimensions are always within u32 for any real display.
        #[allow(clippy::cast_possible_truncation)]
        let width = info.width as u32;
        #[allow(clippy::cast_possible_truncation)]
        let height = info.height as u32;
        #[allow(clippy::cast_possible_truncation)]
        let bpp = info.bytes_per_pixel as u32;
        // stride from bootloader_api is in **pixels** per row (not bytes).
        #[allow(clippy::cast_possible_truncation)]
        let stride = info.stride as u32;
        // `into_buffer()` takes ownership of the FrameBuffer and returns a
        // `'static mut [u8]` pointing to the mapped GOP framebuffer.
        // SAFETY: The bootloader maps and exclusively hands off the
        // framebuffer buffer. No other code aliases it after this point.
        let buf_ptr = raw.into_buffer().as_mut_ptr();
        unsafe {
            FrameBuffer::new(buf_ptr, width, height, bpp, stride, format)
        }
    });

    // Step 3 — heap region selection + one-shot install.
    //
    // `pick_region` returns the **physical** base address of the chosen
    // Usable region (per its current contract; see the host-side
    // `tests/boot_info.rs`). On `bootloader 0.11` with `Mapping::Dynamic`
    // we must translate that into a **virtual** address via the
    // direct-map window before handing it to `BumpHeap::init` — otherwise
    // the kernel ends up dereferencing the raw physical address as if it
    // were virtual, which only happens to work on bootloaders that
    // identity-map low memory (e.g. VirtualBox's path) and faults on
    // QEMU+OVMF / Proxmox where Mapping::Dynamic places RAM behind a
    // direct-map offset (MB9 cross-cutting fix, 2026-05-18).
    let (heap_phys_base, heap_len) =
        omni_kernel::bare_metal::heap::pick_region(&boot_info.memory_regions);
    let phys_offset = boot_info.physical_memory_offset.into_option().unwrap_or(0);
    let heap_virt_base = (heap_phys_base as u64).wrapping_add(phys_offset) as *mut u8;
    // SAFETY: `pick_region` returns a region tagged `Usable`,
    // contiguous, and exclusively owned by the kernel. The direct-map
    // window installed by the bootloader covers all such Usable regions
    // (verified by `kmain::register_direct_mapped_regions` at MB9).
    unsafe {
        omni_kernel::bare_metal::heap::GLOBAL_HEAP.init(heap_virt_base, heap_len);
    }

    // Step 4 — kernel main. Returns `!`.
    omni_kernel::kmain(boot_info, fb)
}
