//! OMNI OS kernel-runner entry point.
//!
//! Specified by [`OIP-Kernel-005`] § S2. This binary is compiled for
//! `x86_64-unknown-none` and is the **bootable** artifact: the
//! bootloader hands `_start` (generated by [`entry_point!`]) the
//! `BootInfo` struct, the runner forwards into `omni_kernel::kmain`,
//! and the kernel either banners-and-halts (K4 scope) or stays alive
//! to handle interrupts (K6+ scope, future OIPs).

#![no_std]
#![no_main]
// Strict lints inherited from the workspace would flag the
// `entry_point!` macro expansion and the kernel-entry function as
// "missing docs", "no panic"-style noises. The lints disabled here
// are exactly those that make sense on host code but not on bare-metal
// kernel entry shims.
#![allow(unsafe_code)]
#![allow(clippy::missing_docs_in_private_items)]

use bootloader::{bootinfo::BootInfo, entry_point};

mod early_console;

entry_point!(kernel_entry);

/// Entry point invoked by the bootloader after UEFI exit-boot-services.
///
/// At K4 the function does three things:
///
/// 1. Initialise the early console (COM1 serial) so any panic from
///    `BumpHeap::init` or `kmain` produces visible output.
/// 2. Select the kernel heap region from the bootloader's memory map
///    via [`omni_kernel::bare_metal::heap::pick_region`] and install
///    it into the global [`omni_kernel::bare_metal::heap::GLOBAL_HEAP`]
///    via the one-shot `init` call from `OIP-Kernel-012` § S2.
/// 3. Hand control to [`omni_kernel::kmain`], which banners and halts.
///
/// The function is `-> !`: the kernel never returns.
fn kernel_entry(boot_info: &'static BootInfo) -> ! {
    // Disable maskable interrupts immediately. The bootloader may not
    // have masked them, and without an IDT in place, any hardware IRQ
    // (PIC timer, etc.) would triple-fault the CPU before the kernel
    // can emit a single byte of diagnostics.
    omni_kernel::bare_metal::arch::interrupts::disable();

    // Initialise the 16550 UART on COM1 to a known-good state before
    // any serial writes. The bootloader firmware may leave DLAB set or
    // the FIFO in an unknown state; this resets it to 8N1 / 115200.
    omni_kernel::bare_metal::early_console::init();

    // Step 1 — early console. No allocation required (the kernel
    // heap is not yet initialised). Spin on the UART line-status
    // register; byte-by-byte writes only.
    early_console::announce_boot();

    // Step 2 — heap region selection + one-shot install. `pick_region`
    // panics with a structured message if no Usable region of at least
    // `MIN_HEAP_BYTES` exists; the K3 panic handler routes that to the
    // serial console and halts.
    let (heap_base, heap_len) =
        omni_kernel::bare_metal::heap::pick_region(&boot_info.memory_map);
    // SAFETY: `pick_region` returns a region tagged `Usable`,
    // contiguous, and now exclusively owned by the kernel for the
    // remainder of the boot. `init` is called exactly once per boot
    // (the bootloader entry point is invoked exactly once).
    unsafe {
        omni_kernel::bare_metal::heap::GLOBAL_HEAP.init(heap_base, heap_len);
    }

    // Step 3 — kernel main. Returns `!`; nothing past this line
    // executes.
    omni_kernel::kmain(boot_info)
}
